//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataEns.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angebot
    {
        public int AngebotID { get; set; }
        public string Firmenname { get; set; }
        public string Adresse { get; set; }
        public string PLZ { get; set; }
        public string Stadt { get; set; }
        public string AngebotNr { get; set; }
        public string Insgessamt { get; set; }
        public string FirmenNameEnssol { get; set; }
        public string TelefonEnssol { get; set; }
        public string AdresseEnssol { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
